//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3643 版自动生成。
// 
namespace HL.BLL.sap300.checkInPurOrderSummit {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZMES_BIAOZHUNCAIGOUSHOUHUO", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_BIAOZHUNCAIGOUSHOUHUO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ZMES_BIAOZHUNCAIGOUSHOUHUO() {
            this.Url = "http://10.2.0.7:8000/sap/bc/srt/rfc/sap/zmes_biaozhuncaigoushouhuo/300/zm" +
                "es_biaozhuncaigoushouhuo/zmes_biaozhuncaigoushouhuo";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZMES_BIAOZHUNCAIGOUSHOUHUO:ZMES_BIAOZHUNCA" +
            "IGOUSHOUHUORequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZMES_BIAOZHUNCAIGOUSHOUHUOResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZMES_BIAOZHUNCAIGOUSHOUHUOResponse CallZMES_BIAOZHUNCAIGOUSHOUHUO([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")] ZMES_BIAOZHUNCAIGOUSHOUHUO1 ZMES_BIAOZHUNCAIGOUSHOUHUO) {
            object[] results = this.Invoke("CallZMES_BIAOZHUNCAIGOUSHOUHUO", new object[] {
                        ZMES_BIAOZHUNCAIGOUSHOUHUO});
            return ((ZMES_BIAOZHUNCAIGOUSHOUHUOResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCallZMES_BIAOZHUNCAIGOUSHOUHUO(ZMES_BIAOZHUNCAIGOUSHOUHUO1 ZMES_BIAOZHUNCAIGOUSHOUHUO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CallZMES_BIAOZHUNCAIGOUSHOUHUO", new object[] {
                        ZMES_BIAOZHUNCAIGOUSHOUHUO}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZMES_BIAOZHUNCAIGOUSHOUHUOResponse EndCallZMES_BIAOZHUNCAIGOUSHOUHUO(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZMES_BIAOZHUNCAIGOUSHOUHUOResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_BIAOZHUNCAIGOUSHOUHUO1 {
        
        private ZMES_DELIVERY[] tB_DELIVERYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMES_DELIVERY[] TB_DELIVERY {
            get {
                return this.tB_DELIVERYField;
            }
            set {
                this.tB_DELIVERYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_DELIVERY {
        
        private string mANDTField;
        
        private string dELIVERY_IDField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string dEL_DATEField;
        
        private string dEL_TIMEField;
        
        private string uSERNAMEField;
        
        private decimal wEMNGField;
        
        private string mATNRField;
        
        private string mAKTXField;
        
        private decimal mENGEField;
        
        private string mEINSField;
        
        private string sWERKSField;
        
        private string lGOBEField;
        
        private string eINDTField;
        
        private string bUKRSField;
        
        private string bSARTField;
        
        private string eKGRPField;
        
        private string lIFNRField;
        
        private string lIFNRNAMEField;
        
        private string fWERKSField;
        
        private string sTATEField;
        
        private string rEMARKField;
        
        private string bUD_DATEField;
        
        private string bUD_TIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELIVERY_ID {
            get {
                return this.dELIVERY_IDField;
            }
            set {
                this.dELIVERY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEL_DATE {
            get {
                return this.dEL_DATEField;
            }
            set {
                this.dEL_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEL_TIME {
            get {
                return this.dEL_TIMEField;
            }
            set {
                this.dEL_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME {
            get {
                return this.uSERNAMEField;
            }
            set {
                this.uSERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WEMNG {
            get {
                return this.wEMNGField;
            }
            set {
                this.wEMNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX {
            get {
                return this.mAKTXField;
            }
            set {
                this.mAKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SWERKS {
            get {
                return this.sWERKSField;
            }
            set {
                this.sWERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGOBE {
            get {
                return this.lGOBEField;
            }
            set {
                this.lGOBEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EINDT {
            get {
                return this.eINDTField;
            }
            set {
                this.eINDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BSART {
            get {
                return this.bSARTField;
            }
            set {
                this.bSARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EKGRP {
            get {
                return this.eKGRPField;
            }
            set {
                this.eKGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNRNAME {
            get {
                return this.lIFNRNAMEField;
            }
            set {
                this.lIFNRNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FWERKS {
            get {
                return this.fWERKSField;
            }
            set {
                this.fWERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUD_DATE {
            get {
                return this.bUD_DATEField;
            }
            set {
                this.bUD_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUD_TIME {
            get {
                return this.bUD_TIMEField;
            }
            set {
                this.bUD_TIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_BIAOZHUNCAIGOUSHOUHUOResponse {
        
        private string rETMSGField;
        
        private string rETVALField;
        
        private ZMES_DELIVERY[] tB_DELIVERYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETMSG {
            get {
                return this.rETMSGField;
            }
            set {
                this.rETMSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETVAL {
            get {
                return this.rETVALField;
            }
            set {
                this.rETVALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMES_DELIVERY[] TB_DELIVERY {
            get {
                return this.tB_DELIVERYField;
            }
            set {
                this.tB_DELIVERYField = value;
            }
        }
    }
}
