//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3643 版自动生成。
// 
namespace HL.BLL.SAP300_SetFactoryOrderCheckIn {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZMES_FACTORYCAIGOUSHOUHUO", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_FACTORYCAIGOUSHOUHUO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ZMES_FACTORYCAIGOUSHOUHUO() {
            this.Url = "http://r3dev01.heli.com:8000/sap/bc/srt/rfc/sap/zmes_factorycaigoushouhuo/300/zme" +
                "s_factorycaigoushouhuo/zmes_factorycaigoushouhuo";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZMES_FACTORYCAIGOUSHOUHUO:ZMES_FACTORYCAIG" +
            "OUSHOUHUORequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZMES_FACTORYCAIGOUSHOUHUOResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZMES_FACTORYCAIGOUSHOUHUOResponse CallZMES_FACTORYCAIGOUSHOUHUO([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")] ZMES_FACTORYCAIGOUSHOUHUO1 ZMES_FACTORYCAIGOUSHOUHUO) {
            object[] results = this.Invoke("CallZMES_FACTORYCAIGOUSHOUHUO", new object[] {
                        ZMES_FACTORYCAIGOUSHOUHUO});
            return ((ZMES_FACTORYCAIGOUSHOUHUOResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCallZMES_FACTORYCAIGOUSHOUHUO(ZMES_FACTORYCAIGOUSHOUHUO1 ZMES_FACTORYCAIGOUSHOUHUO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CallZMES_FACTORYCAIGOUSHOUHUO", new object[] {
                        ZMES_FACTORYCAIGOUSHOUHUO}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZMES_FACTORYCAIGOUSHOUHUOResponse EndCallZMES_FACTORYCAIGOUSHOUHUO(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZMES_FACTORYCAIGOUSHOUHUOResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_FACTORYCAIGOUSHOUHUO1 {
        
        private ZMES_RECEIPT[] tB_RECEIPTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMES_RECEIPT[] TB_RECEIPT {
            get {
                return this.tB_RECEIPTField;
            }
            set {
                this.tB_RECEIPTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_RECEIPT {
        
        private string mANDTField;
        
        private string dELIVERY_IDField;
        
        private string uSERNAMEField;
        
        private string mATNRField;
        
        private string mAKTXField;
        
        private string bUKRSField;
        
        private string bSARTField;
        
        private string eKGRPField;
        
        private string dEL_DATEField;
        
        private string dEL_TIMEField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        private decimal wEMNGField;
        
        private decimal mENGEField;
        
        private string mEINSField;
        
        private string sWERKSField;
        
        private string sLGOBEField;
        
        private string eINDTField;
        
        private string lIFNRField;
        
        private string lIFNRNAMEField;
        
        private string fWERKSField;
        
        private string fLGOBEField;
        
        private string sTATEField;
        
        private string rEMARKField;
        
        private string bUD_DATAField;
        
        private string bUD_TIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELIVERY_ID {
            get {
                return this.dELIVERY_IDField;
            }
            set {
                this.dELIVERY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME {
            get {
                return this.uSERNAMEField;
            }
            set {
                this.uSERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX {
            get {
                return this.mAKTXField;
            }
            set {
                this.mAKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BSART {
            get {
                return this.bSARTField;
            }
            set {
                this.bSARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EKGRP {
            get {
                return this.eKGRPField;
            }
            set {
                this.eKGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEL_DATE {
            get {
                return this.dEL_DATEField;
            }
            set {
                this.dEL_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEL_TIME {
            get {
                return this.dEL_TIMEField;
            }
            set {
                this.dEL_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WEMNG {
            get {
                return this.wEMNGField;
            }
            set {
                this.wEMNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SWERKS {
            get {
                return this.sWERKSField;
            }
            set {
                this.sWERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SLGOBE {
            get {
                return this.sLGOBEField;
            }
            set {
                this.sLGOBEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EINDT {
            get {
                return this.eINDTField;
            }
            set {
                this.eINDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNRNAME {
            get {
                return this.lIFNRNAMEField;
            }
            set {
                this.lIFNRNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FWERKS {
            get {
                return this.fWERKSField;
            }
            set {
                this.fWERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FLGOBE {
            get {
                return this.fLGOBEField;
            }
            set {
                this.fLGOBEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUD_DATA {
            get {
                return this.bUD_DATAField;
            }
            set {
                this.bUD_DATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUD_TIME {
            get {
                return this.bUD_TIMEField;
            }
            set {
                this.bUD_TIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_FACTORYCAIGOUSHOUHUOResponse {
        
        private string rETMSGField;
        
        private string rETVALField;
        
        private ZMES_RECEIPT[] tB_RECEIPTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETMSG {
            get {
                return this.rETMSGField;
            }
            set {
                this.rETMSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETVAL {
            get {
                return this.rETVALField;
            }
            set {
                this.rETVALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMES_RECEIPT[] TB_RECEIPT {
            get {
                return this.tB_RECEIPTField;
            }
            set {
                this.tB_RECEIPTField = value;
            }
        }
    }
}
