//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3643 版自动生成。
// 
namespace HL.BLL.SAP300_GetFactoryOrderCheckIn {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZMES_PURCHASE_SINGLE_DATA", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_PURCHASE_SINGLE_DATA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ZMES_PURCHASE_SINGLE_DATA() {
            this.Url = "http://r3dev01.heli.com:8000/sap/bc/srt/rfc/sap/zmes_purchase_single_data/300/zme" +
                "s_purchase_single_data/zmes_purchase_single_data";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZMES_PURCHASE_SINGLE_DATA:ZMES_PURCHASE_SI" +
            "NGLE_DATARequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZMES_PURCHASE_SINGLE_DATAResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZMES_PURCHASE_SINGLE_DATAResponse CallZMES_PURCHASE_SINGLE_DATA([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")] ZMES_PURCHASE_SINGLE_DATA1 ZMES_PURCHASE_SINGLE_DATA) {
            object[] results = this.Invoke("CallZMES_PURCHASE_SINGLE_DATA", new object[] {
                        ZMES_PURCHASE_SINGLE_DATA});
            return ((ZMES_PURCHASE_SINGLE_DATAResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCallZMES_PURCHASE_SINGLE_DATA(ZMES_PURCHASE_SINGLE_DATA1 ZMES_PURCHASE_SINGLE_DATA, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CallZMES_PURCHASE_SINGLE_DATA", new object[] {
                        ZMES_PURCHASE_SINGLE_DATA}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZMES_PURCHASE_SINGLE_DATAResponse EndCallZMES_PURCHASE_SINGLE_DATA(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZMES_PURCHASE_SINGLE_DATAResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_PURCHASE_SINGLE_DATA1 {
        
        private string eBELNField;
        
        private ZMES_PURCHASE_UB[] tB_EKPOField;
        
        private ZMES_LGORT[] tB_LGORTField;
        
        private string uSERNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMES_PURCHASE_UB[] TB_EKPO {
            get {
                return this.tB_EKPOField;
            }
            set {
                this.tB_EKPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMES_LGORT[] TB_LGORT {
            get {
                return this.tB_LGORTField;
            }
            set {
                this.tB_LGORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME {
            get {
                return this.uSERNAMEField;
            }
            set {
                this.uSERNAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_PURCHASE_UB {
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string bUKRSField;
        
        private string bSARTField;
        
        private string eKGRPField;
        
        private string lIFNRField;
        
        private string lIFNRNAMEField;
        
        private string fWERKSField;
        
        private string fLGOBEField;
        
        private string mATNRField;
        
        private string mATNR_OUTField;
        
        private string mAKTXField;
        
        private string mAKTX_OUTField;
        
        private string aUFNRField;
        
        private decimal mENGEField;
        
        private decimal oBMNGField;
        
        private string mEINSField;
        
        private string sWERKSField;
        
        private string sLGOBEField;
        
        private string eINDTField;
        
        private string rEMARKField;
        
        private decimal wEMNGField;
        
        private decimal wAMNGField;
        
        private string mEMO1Field;
        
        private string mEMO2Field;
        
        private string mEMO3Field;
        
        private string mEMO4Field;
        
        private string mEMO5Field;
        
        private string mEMO6Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BSART {
            get {
                return this.bSARTField;
            }
            set {
                this.bSARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EKGRP {
            get {
                return this.eKGRPField;
            }
            set {
                this.eKGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNRNAME {
            get {
                return this.lIFNRNAMEField;
            }
            set {
                this.lIFNRNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FWERKS {
            get {
                return this.fWERKSField;
            }
            set {
                this.fWERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FLGOBE {
            get {
                return this.fLGOBEField;
            }
            set {
                this.fLGOBEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR_OUT {
            get {
                return this.mATNR_OUTField;
            }
            set {
                this.mATNR_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX {
            get {
                return this.mAKTXField;
            }
            set {
                this.mAKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX_OUT {
            get {
                return this.mAKTX_OUTField;
            }
            set {
                this.mAKTX_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AUFNR {
            get {
                return this.aUFNRField;
            }
            set {
                this.aUFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal OBMNG {
            get {
                return this.oBMNGField;
            }
            set {
                this.oBMNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SWERKS {
            get {
                return this.sWERKSField;
            }
            set {
                this.sWERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SLGOBE {
            get {
                return this.sLGOBEField;
            }
            set {
                this.sLGOBEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EINDT {
            get {
                return this.eINDTField;
            }
            set {
                this.eINDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WEMNG {
            get {
                return this.wEMNGField;
            }
            set {
                this.wEMNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WAMNG {
            get {
                return this.wAMNGField;
            }
            set {
                this.wAMNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMO1 {
            get {
                return this.mEMO1Field;
            }
            set {
                this.mEMO1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMO2 {
            get {
                return this.mEMO2Field;
            }
            set {
                this.mEMO2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMO3 {
            get {
                return this.mEMO3Field;
            }
            set {
                this.mEMO3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMO4 {
            get {
                return this.mEMO4Field;
            }
            set {
                this.mEMO4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMO5 {
            get {
                return this.mEMO5Field;
            }
            set {
                this.mEMO5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEMO6 {
            get {
                return this.mEMO6Field;
            }
            set {
                this.mEMO6Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_LGORT {
        
        private string lGORTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMES_PURCHASE_SINGLE_DATAResponse {
        
        private string rETMSGField;
        
        private string rETVALField;
        
        private ZMES_PURCHASE_UB[] tB_EKPOField;
        
        private ZMES_LGORT[] tB_LGORTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETMSG {
            get {
                return this.rETMSGField;
            }
            set {
                this.rETMSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETVAL {
            get {
                return this.rETVALField;
            }
            set {
                this.rETVALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMES_PURCHASE_UB[] TB_EKPO {
            get {
                return this.tB_EKPOField;
            }
            set {
                this.tB_EKPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMES_LGORT[] TB_LGORT {
            get {
                return this.tB_LGORTField;
            }
            set {
                this.tB_LGORTField = value;
            }
        }
    }
}
