//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3643 版自动生成。
// 
namespace HL.BLL.SAP300_QueryMaterialKuCun {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“Policy”。
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZMATERIAL_AVAILABILITY", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMATERIAL_AVAILABILITY : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ZMATERIAL_AVAILABILITY() {
            this.Url = "http://r3dev01.heli.com:8000/sap/bc/srt/rfc/sap/zmaterial_availability/300/zmater" +
                "ial_availability/zmaterial_availability";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZMATERIAL_AVAILABILITY:ZMATERIAL_AVAILABIL" +
            "ITYRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZMATERIAL_AVAILABILITYResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZMATERIAL_AVAILABILITYResponse CallZMATERIAL_AVAILABILITY([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")] ZMATERIAL_AVAILABILITY1 ZMATERIAL_AVAILABILITY) {
            object[] results = this.Invoke("CallZMATERIAL_AVAILABILITY", new object[] {
                        ZMATERIAL_AVAILABILITY});
            return ((ZMATERIAL_AVAILABILITYResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCallZMATERIAL_AVAILABILITY(ZMATERIAL_AVAILABILITY1 ZMATERIAL_AVAILABILITY, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CallZMATERIAL_AVAILABILITY", new object[] {
                        ZMATERIAL_AVAILABILITY}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZMATERIAL_AVAILABILITYResponse EndCallZMATERIAL_AVAILABILITY(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZMATERIAL_AVAILABILITYResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMATERIAL_AVAILABILITY1 {
        
        private ZAVAILABILITY1[] zKCSLBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZAVAILABILITY1[] ZKCSLB {
            get {
                return this.zKCSLBField;
            }
            set {
                this.zKCSLBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZAVAILABILITY1 {
        
        private string zPLANTField;
        
        private string zMATERIALField;
        
        private string zSTGE_LOCField;
        
        private decimal zAV_QTY_PLTField;
        
        private string tIOSNOField;
        
        private string tIOTASKQTYField;
        
        private string tIOUNITField;
        
        private string tIOFINIQTYField;
        
        private string mATCANOVERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZPLANT {
            get {
                return this.zPLANTField;
            }
            set {
                this.zPLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZMATERIAL {
            get {
                return this.zMATERIALField;
            }
            set {
                this.zMATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZSTGE_LOC {
            get {
                return this.zSTGE_LOCField;
            }
            set {
                this.zSTGE_LOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ZAV_QTY_PLT {
            get {
                return this.zAV_QTY_PLTField;
            }
            set {
                this.zAV_QTY_PLTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIOSNO {
            get {
                return this.tIOSNOField;
            }
            set {
                this.tIOSNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIOTASKQTY {
            get {
                return this.tIOTASKQTYField;
            }
            set {
                this.tIOTASKQTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIOUNIT {
            get {
                return this.tIOUNITField;
            }
            set {
                this.tIOUNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIOFINIQTY {
            get {
                return this.tIOFINIQTYField;
            }
            set {
                this.tIOFINIQTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATCANOVER {
            get {
                return this.mATCANOVERField;
            }
            set {
                this.mATCANOVERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMATERIAL_AVAILABILITYResponse {
        
        private ZAVAILABILITY1[] zKCSLBField;
        
        private string zRETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZAVAILABILITY1[] ZKCSLB {
            get {
                return this.zKCSLBField;
            }
            set {
                this.zKCSLBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRETURN {
            get {
                return this.zRETURNField;
            }
            set {
                this.zRETURNField = value;
            }
        }
    }
}
